const DEFAULT_USER_SERVICE_URL = "http://localhost:8081";
const DEFAULT_JOB_SERVICE_URL = "http://localhost:8082";
const DEFAULT_MATCHING_SERVICE_URL = "http://localhost:8083";

export const USER_SERVICE_URL =
  process.env.NEXT_PUBLIC_USER_SERVICE_URL ?? DEFAULT_USER_SERVICE_URL;

export const JOB_SERVICE_URL =
  process.env.NEXT_PUBLIC_JOB_SERVICE_URL ?? DEFAULT_JOB_SERVICE_URL;

export const MATCHING_SERVICE_URL =
  process.env.NEXT_PUBLIC_MATCHING_SERVICE_URL ?? DEFAULT_MATCHING_SERVICE_URL;
